sul-cidr/pianolatron

src/components/SamplePlayer.js

I'm not sure how long we'll continue using this particular gh-pages site for the MIDI files and MP3 files (and maybe other files, eventually), but `piano_rolls` just seemed like a more appropriate base path than `javatron`.

Update gh-pages URL path for MIDI and MP3 files

---

package.json
snowpack.config.js
src/components/RollDetails.svelte
src/globals.scss
src/index.html
src/styles.scss
svelte.config.js
yarn.lock

This PR adds SCSS support, both to snowpack and to svelte components.  A `globals.scss` and a `styles.scss` are added to the root of the `src/` tree -- as these represent the only (S)CSS I'm expecting outside of svelte components, I figure they're fine there (we can reconsider if there's a need to modularize outside-of-components styles).

Support SCSS

---

package.json
src/App.svelte
src/components/RollViewer.svelte
yarn.lock

I had originally planned for this to be more feature-complete before PR-ing, but I think it's best I ask you to take a look at this now and we get the basic functionality in.  Panning the roll vertically and having the audio sync was giving me a headache, and I want to work on something else for a bit and come back to it :)  (I also have a thought about how that might be implemented differently, perhaps? better.)
Notes on this PR:
1) Zooming and horizontal panning should be rock solid -- if they're not in any environment for any reason, please let me know (can wait until merged and pushed to `gh-pages` for ease of testing on, e.g., mobile devices).
2) This implementation calls `panViewportToTick` on every tick (effectively from `midiSamplePlayer.on("play")`.  You have a note in the …

Roll Viewer

---

src/App.svelte
src/components/Keyboard.svelte
src/components/PlaybackControls.svelte
src/components/RollDetails.svelte
src/components/RollSelector.svelte
src/components/RollViewer.svelte
src/globals.scss
src/styles.scss
src/ui-components/Notification.svelte

This is a start on rearranging the components into something resembling an interface.  See what you think.  It's all provisional and up-for-grabs, of course.
1) When the background colour is anything other that white, the white non-transparent background on the roll images is a bit obnoxious, so there's a solution here that uses CSS blend modes to make the white bits match the chosen `$background-color`.  There are some downsides to this, and it will only work for flat background colours, but I sorta feel like it's this (or something very like it) or a plain white background, tbh -- interested to know what you think.  I do have a commit on the [`manual-blend`](https://github.com/sul-cidr/pianolatron/tree/manual-blend) branch which does basically the same thing but calculates the needed …

Layout rearrangement

---

src/App.svelte
src/assets/json/dj406yq6980.json
src/assets/json/kr397bv2881.json
src/assets/json/pz594dj8436.json
src/assets/json/rx870zt5437.json
src/assets/json/wt621xq0875.json
src/assets/json/yj598pj2879.json
src/assets/json/zb497jz4405.json
src/components/RollDetails.svelte

This PR begins the process of drawing on (an) additional file(s) beyond the `.mid` to generate the interface.  As such it also opens the conversation about exactly how to do this :)
For the purposes of getting started, the JSON files have been committed to this repo, but not the script which generates/assembles them, which is presently in a personal repo (the files in this commit were created from this version:  https://github.com/simonwiles/pianolatron-data/blob/1cf25ed677ff24b1cd0bb0b877c9e785dc7c1215/build-metadata.py).  We need to decide how much of this apparatus belongs here, how much in a separate (presumably sul-cidr) repo, and how much should be considered transient artifacts that aren't persisted (e.g. the MODS, midi, and .txt files that are needed to generate the JSON).
There …

Read json metadata

---

src/App.svelte
src/components/RollViewer.svelte

Using HTML-based overlays for all holes absolutely tanks performance, as you discovered with the prototype, and I couldn't find a way to do anything about that (OSD recalculates the positioning and size of every element when the viewer pans -- I'm not sure it really needs to tbh, but I didn't fancy delving far enough in to it right now to try to improve the behaviour, much less put together something that could be PR'd upstream).
A single SVG overlay works great, because OSD is only aware of the top level element, and the browser/SVG takes care of the rest.  The problem is that styling options are very limited with the SVG route (can't apply `mix-blend-mode` or similar differentially on individual elements within the SVG; dimensions are scaled with the SVG, rather than staying the same …

Double overlays

---

src/App.svelte
src/components/RollViewer.svelte

This is a first pass at some roll viewer controls.  The ones OpenSeadragon provides aren't really what we want, and the options for customizing them are such that we are better off just doing our own.
This PR includes basic functionality -- I'm expecting a subsequent PR to address:
1) making the fit-to-width and center buttons work when the roll is playing;
2) add automatic `disabled` styling to indicate when max/min zoom has been reached, and when the roll is already centered / at fit-to-width;
3) probably refactor into a separate Svelte component;
4) other things?

Roll viewer controls

---

src/components/RollViewer.svelte
src/components/RollViewerControls.svelte

Here are a couple more updates for the roll viewer controls, then.  The user-facing changes are:
1) the buttons are now disabled when their use isn't appropriate (imo this is quite important for decent UX);
2) the fit-to-width icon is changed a little.  I'm not sure anything much more detailed is going to work well at this size, so I did this quickly.  Willing to revise again as needed;
3) you can now fit-to-width successfully while the roll is playing (this will have to be revisited, I expect, in order to make scrubbing and/or vertical panning possible, but that's for later);
4) I dropped the 'center' button -- it poses a number of technical and UI issues, and the functionality isn't actually very useful imo; again, willing to reconsider.

Roll viewer controls pt. 2

---

src/App.svelte
src/components/RollViewer.svelte

This is the best I've been able to get this so far, then (looks awful simple when you look at the overall diff!).
* Vertical panning works nicely when the roll is stopped.  There could perhaps be a conversation to be had around the sensitivity settings.  The panning is using OpenSeadragon's native implementation, and it does expose some values we could easily adjust.
* The panning works very comfortably while playing on the Chromium-based browsers, and fails (but tolerably so) on FF.
* Ctrl+Mousewheel (on the roll image) scrolls the roll (I assume this maps to Cmd+Mousewheel on Macs -- it's only just occurred to me now to think about that).  The scroll increment is 10% of the viewport height per event, which feels comfortable to me.  We may have the whole scroll-direction inversion Macs …

Vertical panning and wheeling

---

src/components/RollViewer.svelte
src/components/RollViewerControls.svelte

Some buttons for those who don't have a <kbd>ctrl</kbd>/<kbd>cmd</kbd> key (also better discoverability etc.).
A couple of things thrown up by this:
1) Previously the <kbd>ctrl</kbd>/<kbd>cmd</kbd> + mousewheel thing was moving in opposite directions depending on the direction of the roll.  This was not intentional on my part (!), but perhaps you noticed and liked it?
2) It's possible to scroll off the ends of the roll and into infinity, it seems (with buttons or mousewheel).
3) Not directly related to this PR, but I noticed while testing:  using the zoom functionality can cause the red line "tracker bar" indicator to get out of sync with where the actually playback position is.  This is a little unpolished.
I consider (2) and (3) to be fairly minor polishing issues that I'm inclined to …

Vertical panning buttons

---

src/App.svelte
src/mq-store.js
src/stores.js

These are some updates to the Svelte stores that have been sitting in my working branches for a while and need to be merged to support some future changes.  In particular, the `media` store allows adapting layout and behaviour in Svelte components by using `{#if $media.narrow} <-- -> {/if}` blocks and so on.

Store updates

---

src/App.svelte
src/components/Keyboard.svelte
src/components/KeyboardControls.svelte
src/stores.js
src/styles/z-index.scss

I don't think there's too much to be said about this -- hopefully it "just works".
* I had been intending a second button to slide the keyboard out but *not* overlay it on the roll image (i.e. just to turn the keyboard off) -- this may still be appropriate.
* Also the button styling isn't ideal.  There's a bit of fragmentation between the different overlay buttons that could (and probably should/will) be addressed at some point; in this case I didn't want to use the CSS-only approach that I used for the collapsible sidebars because I really wanted the keyboard component destroyed and out of the DOM altogether when not on screen.
* The icon is not ideal either, but probably acceptable?  I toyed with creating something new and entirely bespoke, but decided to move on to other things …

Overlay Keyboard

---

src/App.svelte
src/components/KeyboardShortcuts.svelte
src/components/RollViewer.svelte
src/components/SamplePlayer.svelte
src/index.html
src/utils.js

This wound up a bit more unruly (a bit less ruly?) than I'd intended, but here's what's here (in order):
* URL fix for the little CIDR "i"
* A couple of linting commits
* Fix for velocity computations (`midi-player-js` returns a value between 0 and 100, not between 0 and 127)
* All the rest are ultimately targeted at preventing panning/scrolling off the ends of the roll, and handling associated playback behaviour (especially when beyond the range of the actual note holes).  This ended up involving a minor refactor of some of the `<SamplePlayer/>` internals to expose a more optimal API to the main app component.  The other user-facing change that got caught up in this process is that the roll no longer automatically returns to the beginning when the playback reaches the end.  This was …

Misc Fixes

---

src/components/RollSelector.svelte
src/ui-components/FilteredSelect.svelte
src/ui-components/FlexCollapsible.svelte

There are a couple of "Select2"-type components out there for Svelte that can be `npm install`ed (or `yarn add`ed, I suppose), but they're all a bit heavy and over-featured for this case, none had a really perfect UX, and most importantly all the ones I could find were lacking in at least one important respect, so would have needed some kind of hacking anyway.  This is written from scratch to meet our needs specifically.
It should be fully keyboard accessible/driveable, and will accept multiple "words" (e.g. type "bee lam").  I think it's pretty robust at this point (with the caveats listed below).  Please let me know if there are any UI/UX problems or niggles.
A couple of improvements/additions remain outstanding:
* Roll-type filtering (I think I know how I'd like to do it)
* Stripping …

<FilteredSelect/> component for <RollSelector/>

---

src/components/SamplePlayer.svelte

This doesn't add much in terms of visible user-facing functionality except:
1) you can watch the pedals go up and down as you scroll a non-playing roll;
2) you can re-enable roll pedaling in the middle of a roll and have the pedals activated as appropriate without having to wait for the next relevant event.
I think that's basically it.  But this was needed, and paves the way for the same thing to be done with the activeKeys store so that the keyboard behaves the same way.

Pedaling Map

---

src/components/RollViewer.svelte

For the 88-note rolls, which recently received better playback/note highlighting support, the current panning constraints disallow upward panning via the up/down panning buttons or <kbd>ctrl</kbd>-mousewheel at a short, seemingly arbitrary distance up the roll (the location actually is related to the difference between the image length and the pixel location of the first "tick") and allow downward panning to way beyond the bottom (start) of the roll. This adjustment to the clamping limits fixes both issues.

Fix upward, downward panning limits for upward scrolling rolls

---

src/components/RollSelector.svelte
src/components/RollViewer.svelte
src/ui-components/FilteredSelect.svelte
src/ui-components/FlexCollapsible.svelte

This PR fixes a couple of incidental issues (the first two commits), and then adds some rich styling options to the dropdown list items and the input field itself.  It does this by proving a `postMarkup()` hook that allows parent components to alter the display of the various elements *after* they've been filtered and marked up for matches.  In order to make this possible for the input box too, the `<input type="text"/>` element has been replaced with a `<span contenteditable="true"/>`.
This gives lots of flexibility, and from a purely aesthetic point of view I like the way it looks now.  However, the way I've split up the label number is probably controversial/flat-out wrong.  The numbers don't appear to conflict at all, but I assume that's just a fluke?  Anyway, I assume we'll probably …

`<RollSelector/>` rich formatting and adding label numbers

---

.prettierignore
src/components/PlaybackControls.svelte
src/components/RollSelector.svelte
src/styles/base.scss
src/ui-components/FilteredSelect.svelte

This is a collection of miscellaneous updates that I would like to get in before tomorrow's meeting.
* The `<RollSelector/>` dropdown should close if you click on the input field while it's open.
* `build/**` should be excluded from the prettier check in `yarn lint`.
* I've tried forcing the fixed-width font for `<kbd/>` elements (i.e. the keyboard shortcut indicators).  I noticed the look badly out of alignment on Macs, and suppose this is the result of different systems selecting a different typeface for `monospace`, so I've tried forcing it to use "Courier New" on all systems.
* "Stop" is changed to "Rewind" -- temporary thing, but the commit's been sitting on a random local branch for weeks, so it might as well go in here.

Misc. Updates

---

src/App.svelte
src/components/RollViewer.svelte
src/ui-components/FilteredSelect.svelte
src/ui-components/Notification.svelte

The Aristotelian _teloi_ for these changes are:
1. To display a notification if a malformed or otherwise unavailable DRUID is provided in the querystring.
2. To have the app behave more like a proper SPA when updating the querystring (and therefore the URL) either from the dropdown or using the browser back/forward buttons.
To achieve the former, it was necessary to allow for the creation of "unclosable" notifications, which in turn necessitated some updates to handling of `window.onClick` events in the `<RollSelector/>` and `<RollViewer/`> components.  To allow the latter, some additional routing logic and fallbacks were required.
There are two (well, at least two ;)) possibly problematic parts of this PR that I'd like to draw attention to:
1. To close the `<RollSelector/>` dropdown when …

Misc. Fixes and Updates

---

src/components/SamplePlayer.svelte

This PR is to address the issue with toggling roll acceleration emulation not working properly.  The issue was that the `"Set tempo"` events that `midiplayer-js` fires occur **after** the tempo has already been altered.  This means that a) there's no need to listen for these events and manually adjust the tempo in response to them; and b) ignoring these events when `$useMidiTempoEventsOnOff === false` has no effect.  Fortunately our MIDI files have the tempo events on the first MIDI track which otherwise contains only metadata (i.e. no notes) -- so we can simply toggle this track to enable/disable tempo events from the MIDI with no side-effects.
After a lot of testing and re-testing, I just removed dozens of lines of debugging code from this branch and it boils down to three lines in and …

Fix emulated tempo bug

---

src/App.svelte
src/components/RollViewer.svelte
src/components/RollViewerControls.svelte
src/utils.js

Dual PR (sorry!  -- commits are clean!):
* Drops brackets when a label number is available but no label name (though presumably there's a cataloging error here?)
* Adjusts the dynamics of the vertical panning buttons to facilitate fine-grained (< hole-by-hole) panning while still allowing their use for navigation.
I'd fiddled with the latter and arrived at these values, but am open to feedback and further suggestions for what (else?) to do with this.

Roll Panning Dynamics and a fix for redundant brackets

---

src/components/SamplePlayer.svelte

This PR just rolls back [this commit](https://github.com/sul-cidr/pianolatron/commit/1e3c5bb05d92ce38072ffea34f4a4df33770e442) from PR #65. It turns out we do need to manually duplicate the MIDI-encoded tempo adjustment events, because if we just let the events be applied as is, they won't incorporate the user-specified tempo coefficient (set via the Tempo slider), with the result that every time the player reaches a tempo event (these are inserted to mimic roll acceleration), the coefficient will not be applied, leading to an erroneous speedup or slowdown of the playback.

Apply user tempo coefficient at MIDI tempo change events

---

.eslintrc.js
package.json
src/components/Keyboard.svelte
yarn.lock

This PR has your commit from the other branch that includes an eslint bump that flags two a11y issues, so it also includes a fix for those.  Finally I've also removed the `eslint-plugin-jsx-a11y` plugin, since it wasn't actually operational anyway.

Dependency and linting house-keeping

---

src/components/RollViewer.svelte

This keeps the overlay flags from getting clipped by the right edge of the viewer. Just allowing the flags to overflow the viewer is problematic both aesthetically and technically. The threshold is set arbitrarily at 80% of the width for now; it could be something like 50%, but I think it's slightly preferable aesthetically for the note hole flags to all point the same way at the default zoom level, and this happens when threshold = 80%.
This doesn't address the possibility that the active overlays (the labels that can appear _above_ the holes on playback) might be clipped, but that rarely if ever happens due to their positioning.

Flip overlay flags to the left when near right edge of viewer

---

src/App.svelte
src/components/RollViewer.svelte
src/components/SamplePlayer.svelte
src/stores.js

This PR replaces the `$playingNow` store with an `$animatePan` store.  The logic is that we don't actually need to disable the panning animation while "navigating", even if that navigation happens during playback.  The approach here is to make `$animatePan` a custom store that resets itself to false after a given interval (set to approximately the animation time) *after* the last `skipToTick` call (effectively making the store behave like a singleton so that it handles the panning buttons and other elements that repeatedly fire events and update `$currentTick`).

Pan Animation Handling

---

src/App.svelte
src/components/BasicSettings.svelte
src/components/RollViewer.svelte
src/components/RollViewerControls.svelte
src/stores.js

* Move the vertical pan buttons to the top
* Set the max value for the tempo slider to 300%
* Fix the position of the nav strip label for upwards-scrolling rolls
* Prevent the tracker bar indicator from extending over the nav strip
* Use ODS's built-in `scrollToZoom` (disables scroll-to-zoom behaviour on the nav strip, preventing odd interaction effects when zooming and panning at the same time)
+ some linting, housekeeping, and code cleanup.

Miscellaneous Updates

---

src/App.svelte
src/components/BasicSettings.svelte
src/components/KeyboardShortcuts.svelte
src/components/PlaybackControls.svelte
src/components/RollViewer.svelte
src/components/RollViewerControls.svelte
src/stores.js
src/styles/base.scss

This PR updates the keyboard command keystrokes to Kumaran's suggested defaults, and creates new keyboard commands where appropriate.  The only bit that's not done is the
```
Tempo increment bigger: W
Tempo increment smaller: Q
Volume increment bigger: [
Volume increment smaller: ]
```
bit, because I'm not 100% sure what to do with that (including -- but not limited to -- from a UI perspective).  Three levels, as now, but with some kind of a toggle switch for each slider?  Does the volume increment apply to bass and treble adjustments too?
Another rough edge:  I'm not entirely sure how/whether to deal with multiple keystrokes mapping to the same commands.  This comes up in two places in the immediate instance:
* the `keyCode`s for numbers are different when the events originate from a …

Keyboard Commands Update

---

.eslintrc.js
src/Pianolatron.svelte
src/components/RollDetails.svelte
src/components/RollSelector.svelte
src/components/RollViewer.svelte
src/lib/tonejs-piano.js
src/lib/utils.js
src/styles/loader.scss
src/ui-components/FilteredSelect.svelte
src/ui-components/Notification.svelte

This PR includes:
1. a fix for mousewheel zooming (this one has been on a couple of branches but hasn't gone in yet -- it should go in here)
2. a fix for the race condition whereby `annotateHoleData()` could be called before the hole data was available (which is blocking deployment of #101 and #100, I think)
3. a fix for the notification not showing when an invalid DRUID is supplied via http get params, which was introduced in #93 
Along with (3), the notification itself has been tweaked and access to the roll selector widget has been made available, so that rather than just having to reload the page without the defective DRUID param, a user can just pick a roll directly from that page load.
(2) was originally intended to be merged along with a more thorough overhaul of the way the hole …

Fixes and updates

---

src/ui-components/FilteredSelect.svelte

When using Safari on Mac OS or iOS, there's an odd bug whereby entering text in the roll selector searchbar and then deleting all of it somehow prompts Safari to leave an invisible `<br>` tag in the input field, which then results in all of the roll names with "br" in them being highlighted until the selector is closed and reopened.
This is one possible fix; there may be better ones.

Fix weird Safari RollSelector searchbar bug

---

src/components/RollViewer.svelte

This change has been confirmed to alleviate the playback slowdowns experienced on relatively recent Mac OS machines running Chromium browsers when playing rolls with complicated overlays (i.e., lots of holes). Firefox on Mac OS does not exhibit this difficulty in shifting large SVGs (at least on the machines available for testing), so it's not affected.
It should be noted that unfortunately, performance issues persist on other platforms, regardless of whether or not the roll has a large SVG overlay: Mac OS Safari, browsers of any type on middling Windows systems, and non-premium Android and iOS devices.
Also, I couldn't figure out whether it's practicable to limit the footprint of each SVG partition, via `viewBox` settings or something else, so that it doesn't span the entire image …

Split SVG holes overlay into partitions, only display sections that overlap with viewer extent

---

src/components/SamplePlayer.svelte
src/lib/tonejs-piano.js

The first commit seems to be the simplest possible fix for the bug whereby pausing a roll with the sustain pedal down, then rewinding the roll, results in the pedal appearing up in the UI, but the ToneJS piano still considers it to be down. Any notes subsequently played, including by restarting the roll playback, will be erroneously sustained until the first "pedal up" event in the playback, or until the user manually toggles the sustain pedal.
The use of `>` rather than `>=` seems to be a legitimate if subtle bug in the ToneJS piano. At least, there seems to be no benefit to only considering a pedal to be down if a time quantum has passed since it was registered as down; it can cause bugs like the one described above, whereas using `>=` appears to have no negative effects.
The second …

Correct subtle shortcomings of piano playback capabilities

---

src/Pianolatron.svelte
src/components/BasicSettings.svelte
src/components/KeyboardShortcutDeltaEditorRow.svelte
src/components/KeyboardShortcutEditor.svelte
src/components/KeyboardShortcutEditorRow.svelte
src/components/KeyboardShortcuts.svelte
src/components/PanelSwitcher.svelte
src/components/RollViewer.svelte
src/components/TabbedPanel.svelte
src/config/controls-config.js
src/config/keyboard-shortcut-config.js
src/lib/stores.js
src/styles/base.scss
src/ui-components/RangeSlider.svelte
src/ui-components/SliderControl.svelte

This PR drops the <kbd>Ctrl</kbd> and <kbd>Shift</kbd> modifiers for volume and tempo key controls, and adds a single configurable "augment" key command for bass volume and tempo ("left hand" -- defaults to <kbd>w</kbd>) and volume and treble volume ("right-hand" -- defaults to <kbd>[</kbd>).
To make the increment values (`delta`, `augmentedDelta`) configurable, slider controls have been added to the "Keyboard Controls" dialog, and since that has become a little crowded now, it's been split into a tabbed arrangement.  I hope you'll agree it's a passable solution to an awkward problem.  A few bits and pieces of the stores, controls, and config had to be shuffled to make this work nicely and it took a fair bit of iterating to get it all working properly, but I think it's ready for …

Add configurable delta values for keyboard controls

---

package.json
yarn.lock

This doesn't seem to cause any problems, at least on Firefox and Chrome for MacOS. It's possible that the update brings some performance improvements, but if so, they're subtle.
This could be folded into a PR with upgrades of other components, if applicable, but is also OK to go in on its own.
The version release notes:
https://github.com/openseadragon/openseadragon/releases/tag/v3.0.0

Upgrade OpenSeadragon to v3.0.0
