.gitignore, bin/gh-deploy.sh, package.json, snowpack.config.js, src/App.svelte
I'm not sure if a fully automated deploy is really appropriate at this stage -- but if we decide it is, it will be simple from here.
=> Add a gh-deploy script

package.json, snowpack.config.js, src/components/PlaybackControls.svelte, src/components/RollDetails.svelte, src/globals.scss, src/index.html, src/styles.scss, src/ui-components/RangeSlider.svelte, svelte.config.js, yarn.lock
This is a sort of initial scaffolding for future presentational components.  Range sliders, in particular, look so different across browsers that some custom styling is almost a requirement.  I've implemented mousewheel scrolling, although it seems in Firefox it only works when the input element has focus, which sucks a bit.  Haven't tested any of this in Safari, either.
The styling of the sliders is very tweakable (and can inherit from `globals.scss` for theming.  We may not want to use these as is, though, and very likely not for all controls.  For the progress bar, in particular, we might want something quite different.  There are also lots of ways these might be improved from a UI/UX point of view, that we can explore should it seem worthwhile.
=> Fancy slider

src/App.svelte, src/components/SamplePlayer.js, src/stores.js
Small PR to add an `activeNotes` store which wraps and exposes a `Set` object.
=> Active Notes

src/App.svelte, src/components/PlaybackControls.svelte, src/components/SamplePlayer.js, src/stores.js
This is preparatory work that makes it trivial to sync automatic roll-viewer panning to playback.  It may prove to be a little simplistic, but we'll only complicate it further if actually necessary.
It will need some battle testing, but it will be appropriate to do that once the roll viewer is actually on the page :)
=> App timing control

package.json, src/App.svelte, src/components/Keyboard.svelte, src/components/RollSelector.svelte, src/components/RollViewer.svelte, src/scss/loader.scss, yarn.lock
Bunch of small fixes -- see individual commit messages for details.
=> Couple of small fixes

src/components/PlaybackControls.svelte, src/components/SamplePlayer.js, src/stores.js
Mechanics of the "accent" button.  Interested in ideas for styling and placement -- I have a couple, but I'm not confident enough in them to even implement them as a conversation starter.
=> Accent button

src/App.svelte, src/components/PlaybackControls.svelte, src/components/RollDetails.svelte, src/components/RollSelector.svelte, src/ui-components/FlexCollapsible.svelte
This is still very much a work-in-progress, and it is quite likely that very little of this will survive in the codebase for very long, but since it seemed to meet with provisional approval today I figured I'd PR it now as a step towards reconciling the various branches and approaches I've been taking to reorganizing the layout.
=> Collapsible Sidebars

src/App.svelte, src/components/PanelSwitcher.svelte, src/components/SettingsPanel.svelte, src/components/TabbedPanel.svelte, src/styles/globals.scss, src/styles/styles.scss, src/ui-components/FlexCollapsible.svelte
So here's a "slide-over" settings panel as somewhere to put feature toggles and so on.  Some notes (in my usual prolix fashion):
* I don't know that I love the UI much at all, tbh.  I'm sort of imagining there may be more than two panels in this position (perhaps depending on the overall layout) which is why I stayed away from a single on/off button.  Will be interested in feedback.
* The layout/design of the the controls in the settings panel is tbd, of course.
* I think the playback controls should probably come out and be visible at all times.  I have some other ideas in this area, and will hopefully get to that soon.
* The theme changer can either a) stay in the final app; b) be dropped immediately; or c) stick around as a way of exposing alternatives for consideration, and then be …
=> Settings panel

src/components/RollViewer.svelte, src/components/SettingsPanel.svelte, src/stores.js
Here's the option to have the note names popup on active holes.  The PR is basically just some CSS and a new `$userSettings` store.  Not much to see here :)
=> Details on active

src/App.svelte, src/components/Keyboard.svelte, src/components/SamplePlayer.js, src/styles/styles.scss
Here are some updates to the `<Keyboard/>` component.  Essentially it's a re-implementation of the CSS for the keys that makes it more-or-less fully scalable in response to the available width, and an 80% implementation of playability (including glissando).  I say 80% because it doesn't have (multi-)touch support yet.  I've just got the necessary ports opened on my laptop's NetDB registration so that I can host a dev. version that I can connect to from a touch device, so I'll clear this bit up fairly soon.  Oh -- there's also a change to the footer, although there's plenty still tbd there I suppose.
=> Keyboard updates

src/App.svelte, src/components/KeyboardShortcuts.svelte, src/components/PlaybackControls.svelte, src/components/PlaybackSettings.svelte, src/components/SamplePlayer.js, src/stores.js
Here are the basic keyboard shortcuts we need.  A couple of notes:
* increment and decrement values can probably be tweaked, and perhaps made configurable?
* the "hints" to indicate available keys leave something to be desired.  I spent some time trying to come up with something but ultimately failed and decided to move on.
* One thing I experimented with re. the above was increment and decrement buttons -- I feel like a reset button is probably appropriate (on a control-by-control basis and/or for all settings at once), and perhaps this is worth considering in the same context.
* This PR (and the whole concept up to this point) has been focused on key controls to interact with playback, but of course we could start adding additional shortcuts to this framework very easily -- perhaps the …
=> Keyboard Shortcuts

src/components/AdvancedSettings.svelte, src/components/BasicSettings.svelte, src/components/KeyboardShortcuts.svelte, src/components/PlaybackControls.svelte, src/components/RollViewer.svelte, src/stores.js, src/styles/base.scss, src/styles/globals.scss, src/ui-components/RangeSlider.svelte
These have been sitting around for a couple of weeks waiting to go in.  This PR includes:
* The gradient background
* A small (probably pointless) adjustment to the range slider handles
* Styling for the keyboard shortcut indicators
My only concern is with the latter -- it does sort of make it look like they should be clickable, and they're not.  Dunno what you think.  I don't think I reckon it's a show-stopper?  (One possible solution would be to make it so they *are* clickable, of course, but I'm not sure it's really worth it?)
=> CSS updates

src/App.svelte, src/components/KeyboardControls.svelte, src/stores.js
These commits have been sitting un-PR'd for a couple of weeks too, and should probably have been part of the last PR, sorry.  Do you find this UI preferable?
=> Button for hiding/showing the Keyboard component

.eslintrc.js, src/ui-components/FilteredSelect.svelte
There's more to come here still, but I didn't want to wait to get your eyes on this.
PR also includes a fix for the dropdown indicator getting left behind when the left panel is collapsed.
=> `<RollSelector/>` searches are accent insensitive

src/components/RollSelector.svelte, src/styles/z-index.scss, src/ui-components/FilteredSelect.svelte
This PR adds faceting on roll type.  The UI is plain, but servicable, I think?  I've not found any bugs, but you usually manage to find something (thank you)!
=> `<RollSelector/>` Faceting

src/App.svelte, src/components/RollSelector.svelte
I think this should cut it for now, at least.  I had to rejig the way (or rather where) the munging of the catalog JSON occurs, but otherwise this is fairly clean.
=> DRUID as URL parameter

src/App.svelte, src/components/RollViewer.svelte, src/components/SamplePlayer.svelte, src/stores.js, src/utils.js
Okay, now that the improved panning behaviour is in, we can do the key highlighting as we pan / step-through.  This also sets the highlighted keys when jumping / navigating otherwise.
=> Piano keyboard highlighting when panning / navigating

src/components/RollViewer.svelte, src/components/RollViewerControls.svelte, src/utils.js
I'm pretty sure this won't be able to skip over any note-holes now.  Tried a few approaches, but this felt best.
One side-effect -- this effects the mouse-wheel panning too (well, the previous PR did too, but it's exaggerated now).  The mouse-wheel is fine (good, better probably) for stepping through now, but kinda useless for navigating the roll at this point.  For my part I think I'm probably okay with that, given the upcoming nav / mini-map feature, but not sure if you'll agree?
=> Vertical panning fine-tuning

src/ui-components/FilteredSelect.svelte
Are they really facets if you can only select one at a time?  Probably not...
=> Persist `<RollSelector/>` facets

src/components/RollViewerControls.svelte
This PR tidies up the handling of the pan buttons when the button is held down, and applies the identical solution to the zoom buttons.
=> Zoom button handling

src/components/RollViewer.svelte, src/utils.js
Can you okay and merge this when you get chance, please?  Couple of small and (hopefully!) uncontroversial refactors.
=> Minor Refactors

src/components/RollViewer.svelte
This is a draft PR just to invite you to take a look at this.  If we go this way we get this much this easily (although there's still a bit of work to do, of course).  On the other hand, now that I see it, I'm not sure there's much use in the "mini-map", given that you can't see anything at all...  I also experimented with just having a vertical slider, and am considering a hand-rolled solution with one rectangle (`<div/>`) inside another where the former is sized and moves to reflect what is shown in the viewport w/r/t the whole image.
Thoughts and opinions?
=> Mini-map / Navigator ?

src/components/RollViewer.svelte
Some very minor tracker bar styling adjustments -- opinions welcome :)
=> Trackerbar Styling Adjustments

README.md, package.json, src/layouts/base.astro, src/styles/styles.scss, src/tonejs-piano.js, src/ui-components/FilteredSelect.svelte, yarn.lock
This PR is mostly dependency bumps (want to keep up with Astro in particular), but also bumps all the linting and formatting dependencies, and updates a couple of source code files as a direct result.  Finally, this PR also includes the addition of a couple of new `<meta/>` tags in the `<head/>` of rendered pages, stamping in the build date and time and the git commit the deploy was built from.  Often handy.
Will need a quick `rm -rf node_modules && yarn install`.
=> Housekeeping

src/Pianolatron.svelte, src/components/RollViewer.svelte, src/components/RollViewerScaleBar.svelte, src/lib/draggable-action.js
I'm going to open this as a draft PR now.  It has some basic ruler-like styling (the `.us` class is there as a place-holder as this will need to be tweaked for a metric style).  At the moment it fades in where the "Downloading roll images..." fades out, which doesn't seem awful but I'm not wedded to it either.
Open season on this at this point -- how far is it from something you'd be happy with?  Really we could do anything we want with it, so I'd like to hear your wishlist.  A solution is certainly needed for the ticks when we're at multiples (especially odd multiples) of an inch.  Some other possibilities include setting a maximum width, and optimizing the number of "ticks" shown depending on the width.
=> Alternative scalebar

package.json, src/components/KeyboardControls.svelte, src/components/KeyboardShortcutDeltaEditorRow.svelte, src/components/KeyboardShortcutEditor.svelte, src/components/KeyboardShortcutEditorRow.svelte, src/components/RollSelector.svelte, src/components/RollViewerControls.svelte, src/layouts/base.astro, src/styles/css-globals.scss, src/ui-components/Icon.svelte, src/ui-components/IconButton.svelte, src/ui-components/RangeSlider.svelte, yarn.lock
This is a bunch of tiny commits that have been hanging around for ages.  Please merge whenever it's convenient.  Cheers!
=> Misc. Updates

package.json, src/components/RollViewer.svelte, yarn.lock
Only one small code change is needed; tiled source loading performance is allegedly improved.
=> Upgrade Openseadragon dependency
